### ISSUE TITLE
Add Travis matrix for Ubuntu 12.04, 14.04

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-linux-setup#1]
As title.

**Comment by CAMOBAP795** [comment]
@ronaldtse according to recent issues with docker because travis already have many preinstalled software and test isn't very representative, I will provide some suggestions after fix https://github.com/CalConnect/standards.calconnect.org/pull/24

**Comment by ronaldtse** [comment]
Sounds good. Thanks @CAMOBAP795 !

**Comment by ronaldtse** [comment]
The install script used to work on Ubuntu 14.04, but today when I tried it won't work. The reason is the removal of `rbenv` -- 14.04 defaults to Ruby 1.9.3, but it is not supported by Metanorma.

Here we must ensure that `ubuntu.sh` can support Ruby 2.5.

**Comment by CAMOBAP795** [comment]
Was done in #7
