### ISSUE TITLE
IETF: Add xml2rfc and idnits as dependencies

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-linux-setup#10]
Metanorma-IETF depends on xml2rfc and idnits for a full toolchain.

This requires installation of xml2rfc from `pip` and `idnits`, as follows on Ubuntu (see https://github.com/metanorma/rfc-asciirfc-minimal/blob/master/.travis.yml)

```sh
export IDNITS_URL=https://tools.ietf.org/tools/idnits/
export IDNITS_VER=$(curl -Ls $IDNITS_URL | grep -e 'tgz' | sed -e 's/.*\(idnits-.*\).tgz.*/\1/') ; echo ${IDNITS_VER}
curl -SL ${IDNITS_URL}${IDNITS_VER} | tar xzv
export PATH=$(pwd)/${IDNITS_VER}:${PATH}
pip install --user xml2rfc
```

We should include them on Ubuntu, macOS and Windows so that those users can also build IETF documents. Or, we can have a separate script that sets this up.

**Comment by CAMOBAP795** [comment]
@ronaldtse can we install `idnits` from pip too https://pypi.org/project/idnits/ without downloading package manually?

**Comment by ronaldtse** [comment]
Yes of course! It wasn’t available on pip before.

**Comment by CAMOBAP795** [comment]
Done
