### ISSUE TITLE
Use Snap packages to install on Linux if possible

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-linux-setup#13]
A number of distributions now support snap. If snap is available, use snap to install the packages.

**Comment by ronaldtse** [comment]
@CAMOBAP795 key point here: This script works on Docker, but Snap DOES NOT WORK in a Dockerfile. So we need to detect if the script is running insider Docker or not:

* If not in docker, run Snap install
* If in docker, run normal install like today

https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker

**Comment by CAMOBAP795** [comment]
Blocked by https://github.com/metanorma/metanorma-snap/issues/1

**Comment by CAMOBAP** [comment]
@ronaldtse we can implement this task but maybe better if we will keep `metanorma-linux-setup` independent of `metanorma-snap`?

In this case, we will have clear responsibilities:
 - `metanorma-snap` - for snap installation
 - `metanorma-linux-setup` - for installation 'from scratch'

So I think we can leave it up to the end-user. I think it will be easier to manage if the script will not contain this big `IF` and `metanorma-linux-setup` will do a single dedicated thing.

Let me know if you still think that it makes sense to implement it.

**Comment by ronaldtse** [comment]
The original intention to delegate to Snap is so that we only need to manage the Snap build -- then metanorma-linux-build can be simplified.

Right now the `ubuntu.sh` script already relies on Snap:
https://github.com/metanorma/metanorma-linux-setup/blob/9122133f2b885d96aca0e2571753cc9d032e0c6b/ubuntu.sh#L48-L51

What issues do you see if we use Snap here?

**Comment by CAMOBAP** [comment]
oh you are right, we already use snap anyway, @ronaldtse should the script be responsible for installation snap by itself?

**Comment by CAMOBAP** [comment]
Also should ubuntu.sh/centos.sh be responsible for metanorma installation? because previous it installs only dependencies

**Comment by ronaldtse** [comment]
> oh you are right, we already use snap anyway, @ronaldtse should the script be responsible for installation snap by itself?

Yes please (if it's not already installed)

> Also should ubuntu.sh/centos.sh be responsible for metanorma installation? because previous it installs only dependencies

Yes please!

**Comment by CAMOBAP** [comment]
Done
