### ISSUE TITLE
Question: Ubuntu Setup Script

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-linux-setup#15]
Hey guys, looking at [setup script](https://github.com/metanorma/metanorma-linux-setup/blob/master/ubuntu.sh), there are two things that caught my eyes. Do we need the following dependencies for our setup?

* Ruby `ruby-bundler` and `ruby-dev` in the first line
* Installing `nvm` and then install node, why not install `node` directly?

cc: @CAMOBAP795, @ronaldtse

**Comment by CAMOBAP795** [comment]
@abunashir 

 - `ruby-bundler` I suppose this is just alias to `gem install bundler`
 - `ruby-dev` - must-have, because it contains native libraries & headers which need to compile gems with native code
 - `nvm` AFAIK we decided to do as minimal as a possible intervention into existing environment

**Comment by abunashir** [comment]
Normally it installs an old version, so I would leave that up to the user to decide, for example when we were using this with our docker image then we still had to install the latest one, so I don't see a very compelling reason to do that twice.

> @abunashir
> 
> * `ruby-bundler` I suppose this is just alias to `gem install bundler`

Sounds good 👍 

> * `ruby-dev` - must-have, because it contains native libraries & headers which need to compile gems with native code

I see a couple of issues here, first of all, we are forcing the user to use `nvm` (in my experience it's slow and I'm also not sure if our current env export actually persists in user's machine/profile).

so what do you think about adding something like, we try to see if a user already have latest `node` installed or not first and if they don't only then we install the latest version of node directly from the source?

I also have the same opinion about `rvm` in another file, not all user might use `rvm`, some might use `rbenv`. So,  I think what might be useful is to check for ruby version and if they don't have the supported version present then install latest one directly. What do you think?

> * `nvm` AFAIK we decided to do as minimal as a possible intervention into existing environment

**Comment by ronaldtse** [comment]
@abunashir the reasons we use `nvm`:
* the Node bundled in system packages is usually older and requires extensive updating
* we want to be able to control the Node version in the Docker image.

The reasons we use `rvm` are identical. For example, there was a time where 2.6 came out but Metanorma wasn't fully compatible. We had to lock to Ruby 2.5 back then.

Currently, the linux setup script is only used in:
* CI builds
* setting up the Docker image

If we want to check if the currently installed version is good (implies we need to keep a list of that somewhere), that is completely fine.

**Comment by abunashir** [comment]
@ronaldtse: If CI and Docker Image is our only use for this, then I think we are okay.

**Comment by ronaldtse** [comment]
@abunashir I think this script will only be used for our build maintenance:
- Docker
- Package building
- CI

In fact, we should make real packages for RPM, Deb, etc.
