### ISSUE TITLE
Integrate PDF setup into build script

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-linux-setup#21]
Integrate instructions from https://github.com/metanorma/mn-native-pdf/blob/master/README.adoc, as we are now integrating the functionality of that repository into metanorma

**Comment by opoudjis** [comment]
An essential component of this work is to identify the fonts directory on the current system to be used for PDF generation. The README in mn-native-pdf is mac only.

**Comment by ronaldtse** [comment]
> The README in mn-native-pdf is mac only.

The README in mn-native-pdf also handles Ubuntu.

But we need to update the Linux scripts to install the necessary components.

**Comment by CAMOBAP795** [comment]
Blocked by https://github.com/metanorma/metanorma/issues/95

**Comment by CAMOBAP** [comment]
Done
