### ISSUE TITLE
Bug with Ubuntu setup

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-linux-setup#28]
Reported by @douglm 

> In the meantime I tried on a virtual copy of ubuntu. I have just run the first part of the install - that is
```
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
```

and it ends with:

```
idnits-2.16.04/changelog
idnits-2.16.04/control
idnits-2.16.04/idnits
100 60126  100 60126    0     0  97448      0 --:--:-- --:--:-- --:--:-- 97291
idnits-2.16.04/copyright
idnits-2.16.04/todo
idnits-2.16.04/about
bash: line 64: metanorma: command not found
Command 'metanorma setup' finished with errors. Please execute it again before the first metanorma run
```

**Comment by ronaldtse** [comment]
@CAMOBAP can you have a look here? I suspect `metanorma setup` can't be called within the setup script.

**Comment by douglm** [comment]
Just to see what happened I ran the second script:
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash

It runs then I get these errors - I also tried sudo ... - no change

bash: line 22: rvm: command not found
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
mike@mike-VirtualBox:~/rfcs$

**Comment by douglm** [comment]
I think the rvm command not found issue is a path problem. I noticed it was updating .bashrc so I tried

. /home/mike/.bashrc

and rerunning the script - this time i get 


RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.

**Comment by douglm** [comment]
Trying to follow the instructions about terminal emulator prefs - I'm running konsole so I changed the settings according to the rvm site. It made no difference - i still get the warning - perhaps the way the script runs rvm?

**Comment by ronaldtse** [comment]
@CAMOBAP is this fixed? Thanks.

**Comment by CAMOBAP** [comment]
### What we had before

regrading top comment https://github.com/metanorma/metanorma-linux-setup/issues/28#issue-657807818 , originally this script never installed metanorma but prepared environment for it (install all dependencies and rvm)

regarding this comment https://github.com/metanorma/metanorma-linux-setup/issues/28#issuecomment-659132837 , we still need sudo to run install-gems.sh

### What we have right now

 - if `snapd` installed metanorma stable will be installed
 - if there is not `snapd` we will do pretty much the same but install metanorma with gem
 - we covered both these cases in CI https://github.com/metanorma/metanorma-linux-setup/blob/master/.github/workflows/build.yml#L36 and https://github.com/metanorma/metanorma-linux-setup/blob/master/.github/workflows/build.yml#L17 

@douglm can you  confirm that the issue fixed for you?

**Comment by CAMOBAP** [comment]
Should be fixed now

To install metanorma using scripts from scratch please follow https://github.com/metanorma/metanorma-linux-setup#install-on-ubuntu
