### ISSUE TITLE
Add auto-release trigger like metanorma-docker

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-linux-setup#29]

**Comment by CAMOBAP** [comment]
I'm not sure that I understand this right, what exactly should we deliver here?

The script stays untouched, we can just test it on release

@ronaldtse Am I miss something?

**Comment by ronaldtse** [comment]
I think we should create a "release" version of the linux setup script so we know what will work instead of just pointing to `master`. In addition, we really should make GitHub Actions (i.e. actions-mn) work...
