### ISSUE TITLE
Setup too slow for just compiling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-linux-setup#8]
We don't need to run the LaTeX test suite on just compiling Metanorma documents. There should be some environment variable that only with it on, the Perl/LaTeXML tests are run.

Normally we really don't want to run those.

**Comment by ronaldtse** [comment]
@CAMOBAP795 for the `METANORMA_DEBUG` environment variable, can you help update the README to describe it? Then we can close this. Thanks!

**Comment by CAMOBAP795** [comment]
Done but time still round ~20-15min

I didn't comparison according to travis-ci history
 - `./install-gems.sh` time  ~150s for `xenial` and ~400s for `trusty`
 - `latexml` installation from apt-get much faster but it's outdated there

I don't see more options to speed up here, @ronaldtse let me know if you have some idea

**Comment by CAMOBAP795** [comment]
We introduced `METANORMA_DEBUG` environment variable which will:
* Add more verbose logging
* Enable tests on dependent components (like latexml)
